# fly.toml file generated for novabot on 2022-12-03T23:46:05Z

app = "novabot"

[env]
  DISCORD_ALLIED_GUILD_ROLE_ID = "372835643149123584"
  DISCORD_DUNGEONS_BOT_ID = "170915625722576896"
  DISCORD_DUNGEONS_GUILD_ID = "bfc954d7-b717-4cfa-b91f-f82f08b13066"
  DISCORD_ELDER_ROLE_ID = "363839697723850762"
  DISCORD_GUILD_ID = "363833124288987137"
  DISCORD_IRON_ROLE_ID = "541690801252597766"
  DISCORD_MEMBER_ROLE_ID = "363836330486267905"
  DISCORD_MISSING_MEMBERS_CHANNEL_ID = "395019554893463563"
  DISCORD_NO_GUILD_ROLE_ID = "365275624220262411"
  DISCORD_OTHER_GUILD_ROLE_ID = "363868989689954304"
  DISCORD_REQUEST_CHANNEL_ID = "399343802432880650"
  GOOGLE_REDIRECT_URI='http://novabot.fly.dev:3000'
  GOOGLE_SCRIPT_ID = "1RFT5LF1S6lse-VdPwqjFqMwJzFYAsj3-9GBOdnDMdVuwg5314ziAnmDT"
  GOOGLE_SPREADSHEET_ID = "13I_dFYKl6LoDCj9ZFupdO4WSXpIb_N8hTmURU5fo8Co"
  GOOGLE_SPREADSHEET_URL = "https://docs.google.com/spreadsheets/d/13I_dFYKl6LoDCj9ZFupdO4WSXpIb_N8hTmURU5fo8Co/edit#gid=0"
  WEBSITE_URL = "https://takashi-22812.github.io/bank/bank.html"

[build]
  build-target = "runner"
